import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { Camera, LogOut, UserRound } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { LoadingState, NetramTextField, PrimaryButton, SecondaryButton, SectionHeader } from "@/components/netram/ui";
import { useAuth } from "@/hooks/useAuth";
import { supabase } from "@/integrations/supabase/client";
export const Route=createFileRoute("/_authenticated/officer/profile")({head:()=>({meta:[{title:"Officer Profile — NETRAM AI"},{name:"description",content:"Update officer profile information and photograph."},{property:"og:title",content:"Officer Profile — NETRAM AI"},{property:"og:description",content:"Update officer profile information and photograph."}]}),component:Page});
function Page(){const navigate=useNavigate();const {user,profile,loading,setProfile}=useAuth();const [name,setName]=useState(profile?.name??"");const [district,setDistrict]=useState(profile?.district??"");const [busy,setBusy]=useState(false);if(loading||!user)return <LoadingState/>;const userId=user.id;async function upload(file:File){setBusy(true);const path=`${userId}/profile/avatar-${Date.now()}.${file.name.split(".").pop()||"jpg"}`;const up=await supabase.storage.from("inspection-evidence").upload(path,file,{upsert:true});if(up.error){toast.error(up.error.message);setBusy(false);return}const signed=await supabase.storage.from("inspection-evidence").createSignedUrl(path,31536000);const photo=signed.data?.signedUrl??null;const res=await supabase.from("profiles").update({photo_url:photo}).eq("id",userId).select().single();if(res.error)toast.error(res.error.message);else{setProfile(res.data);toast.success("Profile photo updated.")}setBusy(false)}async function save(){setBusy(true);const res=await supabase.from("profiles").update({name,district}).eq("id",userId).select().single();if(res.error)toast.error(res.error.message);else{setProfile(res.data);toast.success("Profile updated.")}setBusy(false)}return <div className="mx-auto max-w-2xl"><SectionHeader title="Officer Profile" subtitle="Keep your identity and assigned district current"/><div className="surface p-6"><div className="mb-6 flex items-center gap-4"><div className="flex h-20 w-20 items-center justify-center overflow-hidden rounded-full bg-primary/10 text-primary">{profile?.photo_url?<img src={profile.photo_url} alt="Officer profile" className="h-full w-full object-cover"/>:<UserRound className="h-8 w-8"/>}</div><label className="inline-flex h-10 cursor-pointer items-center gap-2 rounded-xl border border-border px-4 text-sm font-semibold hover:bg-muted"><Camera className="h-4 w-4"/>Change photo<input type="file" accept="image/*" className="sr-only" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)upload(f)}}/></label></div><div className="space-y-4"><NetramTextField label="Full name" value={name||profile?.name||""} onChange={e=>setName(e.target.value)}/><NetramTextField label="Email" value={profile?.email??user.email??""} disabled/><NetramTextField label="District" value={district||profile?.district||""} onChange={e=>setDistrict(e.target.value)}/><PrimaryButton onClick={save} disabled={busy}>Save profile</PrimaryButton><SecondaryButton className="w-full text-destructive" onClick={async()=>{await supabase.auth.signOut();navigate({to:"/"})}}><LogOut className="h-4 w-4"/>Sign out</SecondaryButton></div></div></div>}
