/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedOfficerRouteRouteImport } from './routes/_authenticated/officer/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAlertsRouteImport } from './routes/admin/alerts'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminCctvRouteImport } from './routes/admin/cctv'
import { Route as AdminInspectionsRouteImport } from './routes/admin/inspections'
import { Route as AdminMapRouteImport } from './routes/admin/map'
import { Route as AdminNgosRouteImport } from './routes/admin/ngos'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AuthAdminRouteImport } from './routes/auth.admin'
import { Route as AuthOfficerRouteImport } from './routes/auth.officer'
import { Route as AdminReportsReportIdRouteImport } from './routes/admin/reports.$reportId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOfficerRouteRoute =
  AuthenticatedOfficerRouteRouteImport.update({
    id: '/officer',
    path: '/officer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAlertsRoute = AdminAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCctvRoute = AdminCctvRouteImport.update({
  id: '/cctv',
  path: '/cctv',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInspectionsRoute = AdminInspectionsRouteImport.update({
  id: '/inspections',
  path: '/inspections',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMapRoute = AdminMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNgosRoute = AdminNgosRouteImport.update({
  id: '/ngos',
  path: '/ngos',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthAdminRoute = AuthAdminRouteImport.update({
  id: '/auth/admin',
  path: '/auth/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOfficerRoute = AuthOfficerRouteImport.update({
  id: '/auth/officer',
  path: '/auth/officer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsReportIdRoute = AdminReportsReportIdRouteImport.update({
  id: '/$reportId',
  path: '/$reportId',
  getParentRoute: () => AdminReportsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/officer': typeof AuthenticatedOfficerRouteRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/cctv': typeof AdminCctvRoute
  '/admin/inspections': typeof AdminInspectionsRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/ngos': typeof AdminNgosRoute
  '/admin/reports': typeof AdminReportsRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/auth/admin': typeof AuthAdminRoute
  '/auth/officer': typeof AuthOfficerRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/reports/$reportId': typeof AdminReportsReportIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/officer': typeof AuthenticatedOfficerRouteRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/cctv': typeof AdminCctvRoute
  '/admin/inspections': typeof AdminInspectionsRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/ngos': typeof AdminNgosRoute
  '/admin/reports': typeof AdminReportsRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/auth/admin': typeof AuthAdminRoute
  '/auth/officer': typeof AuthOfficerRoute
  '/admin': typeof AdminIndexRoute
  '/admin/reports/$reportId': typeof AdminReportsReportIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/officer': typeof AuthenticatedOfficerRouteRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/cctv': typeof AdminCctvRoute
  '/admin/inspections': typeof AdminInspectionsRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/ngos': typeof AdminNgosRoute
  '/admin/reports': typeof AdminReportsRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/auth/admin': typeof AuthAdminRoute
  '/auth/officer': typeof AuthOfficerRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/reports/$reportId': typeof AdminReportsReportIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/reset-password'
    | '/officer'
    | '/admin/alerts'
    | '/admin/analytics'
    | '/admin/cctv'
    | '/admin/inspections'
    | '/admin/map'
    | '/admin/ngos'
    | '/admin/reports'
    | '/admin/users'
    | '/auth/admin'
    | '/auth/officer'
    | '/admin/'
    | '/admin/reports/$reportId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reset-password'
    | '/officer'
    | '/admin/alerts'
    | '/admin/analytics'
    | '/admin/cctv'
    | '/admin/inspections'
    | '/admin/map'
    | '/admin/ngos'
    | '/admin/reports'
    | '/admin/users'
    | '/auth/admin'
    | '/auth/officer'
    | '/admin'
    | '/admin/reports/$reportId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/reset-password'
    | '/_authenticated/officer'
    | '/admin/alerts'
    | '/admin/analytics'
    | '/admin/cctv'
    | '/admin/inspections'
    | '/admin/map'
    | '/admin/ngos'
    | '/admin/reports'
    | '/admin/users'
    | '/auth/admin'
    | '/auth/officer'
    | '/admin/'
    | '/admin/reports/$reportId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  AuthAdminRoute: typeof AuthAdminRoute
  AuthOfficerRoute: typeof AuthOfficerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/officer': {
      id: '/_authenticated/officer'
      path: '/officer'
      fullPath: '/officer'
      preLoaderRoute: typeof AuthenticatedOfficerRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/alerts': {
      id: '/admin/alerts'
      path: '/alerts'
      fullPath: '/admin/alerts'
      preLoaderRoute: typeof AdminAlertsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/cctv': {
      id: '/admin/cctv'
      path: '/cctv'
      fullPath: '/admin/cctv'
      preLoaderRoute: typeof AdminCctvRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/inspections': {
      id: '/admin/inspections'
      path: '/inspections'
      fullPath: '/admin/inspections'
      preLoaderRoute: typeof AdminInspectionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/map': {
      id: '/admin/map'
      path: '/map'
      fullPath: '/admin/map'
      preLoaderRoute: typeof AdminMapRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/ngos': {
      id: '/admin/ngos'
      path: '/ngos'
      fullPath: '/admin/ngos'
      preLoaderRoute: typeof AdminNgosRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/auth/admin': {
      id: '/auth/admin'
      path: '/auth/admin'
      fullPath: '/auth/admin'
      preLoaderRoute: typeof AuthAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/officer': {
      id: '/auth/officer'
      path: '/auth/officer'
      fullPath: '/auth/officer'
      preLoaderRoute: typeof AuthOfficerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports/$reportId': {
      id: '/admin/reports/$reportId'
      path: '/$reportId'
      fullPath: '/admin/reports/$reportId'
      preLoaderRoute: typeof AdminReportsReportIdRouteImport
      parentRoute: typeof AdminReportsRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedOfficerRouteRoute: typeof AuthenticatedOfficerRouteRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedOfficerRouteRoute: AuthenticatedOfficerRouteRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminReportsRouteChildren {
  AdminReportsReportIdRoute: typeof AdminReportsReportIdRoute
}

const AdminReportsRouteChildren: AdminReportsRouteChildren = {
  AdminReportsReportIdRoute: AdminReportsReportIdRoute,
}

const AdminReportsRouteWithChildren = AdminReportsRoute._addFileChildren(
  AdminReportsRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminAlertsRoute: typeof AdminAlertsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCctvRoute: typeof AdminCctvRoute
  AdminInspectionsRoute: typeof AdminInspectionsRoute
  AdminMapRoute: typeof AdminMapRoute
  AdminNgosRoute: typeof AdminNgosRoute
  AdminReportsRoute: typeof AdminReportsRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAlertsRoute: AdminAlertsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCctvRoute: AdminCctvRoute,
  AdminInspectionsRoute: AdminInspectionsRoute,
  AdminMapRoute: AdminMapRoute,
  AdminNgosRoute: AdminNgosRoute,
  AdminReportsRoute: AdminReportsRouteWithChildren,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  AuthAdminRoute: AuthAdminRoute,
  AuthOfficerRoute: AuthOfficerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
